fix: define the missing forwards_subclass_metadata_specific method in the ZipBase class (#377)
## Description

This PR defines the `forwards_subclass_metadata_specific` method in the
`ZipBase `class. This definition seems mandatory as `ZipBase` inherits
from the `Forward`s class which declares an abstract method
`forwards_subclass_metadata_specific`, see:
[https://docs.python.org/3/library/abc.html#abc.abstractmethod](https://docs.python.org/3/library/abc.html#abc.abstractmethod)

## What problem does this change solve?

This change solves the following issue:

```
File "/perm/fra6527/venvs/3-aromeds-dev-7e65c1cb35/lib/python3.11/site-packages/anemoi/training/data/datamodule.py", line 98, in data_indices
    return IndexCollection(self.config, self.ds_train.name_to_index)
                                        ^^^^^^^^^^^^^
  File "/usr/local/apps/python3/3.11.10-01/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/perm/fra6527/venvs/3-aromeds-dev-7e65c1cb35/lib/python3.11/site-packages/anemoi/training/data/datamodule.py", line 103, in ds_train
    open_dataset(
  File "/perm/fra6527/venvs/3-aromeds-dev-7e65c1cb35/lib/python3.11/site-packages/anemoi/datasets/data/__init__.py", line 89, in open_dataset
    ds = _open_dataset(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/perm/fra6527/venvs/3-aromeds-dev-7e65c1cb35/lib/python3.11/site-packages/anemoi/datasets/data/misc.py", line 506, in _open_dataset
    sets.append(_open(a))
                ^^^^^^^^
  File "/perm/fra6527/venvs/3-aromeds-dev-7e65c1cb35/lib/python3.11/site-packages/anemoi/datasets/data/misc.py", line 384, in _open
    return _open_dataset(**a).mutate()
           ^^^^^^^^^^^^^^^^^^
  File "/perm/fra6527/venvs/3-aromeds-dev-7e65c1cb35/lib/python3.11/site-packages/anemoi/datasets/data/misc.py", line 591, in _open_dataset
    sets.append(_open(a))
                ^^^^^^^^
  File "/perm/fra6527/venvs/3-aromeds-dev-7e65c1cb35/lib/python3.11/site-packages/anemoi/datasets/data/misc.py", line 384, in _open
    return _open_dataset(**a).mutate()
           ^^^^^^^^^^^^^^^^^^
  File "/perm/fra6527/venvs/3-aromeds-dev-7e65c1cb35/lib/python3.11/site-packages/anemoi/datasets/data/misc.py", line 534, in _open_dataset
    return zip_factory(args, kwargs).mutate()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/perm/fra6527/venvs/3-aromeds-dev-7e65c1cb35/lib/python3.11/site-packages/anemoi/datasets/data/xy.py", line 283, in zip_factory
    return Zip(datasets, check_compatibility=check_compatibility)._subset(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class Zip with abstract method forwards_subclass_metadata_specific
```

that arises when loading a Zip of datasets during training, e.g. with
the following dataloader config:

```
dataset:
  zip:
    - dataset: ${hardware.paths.data}/${hardware.files.dataset_x}
      name: lres
      select: ${dataloader.select_in}
    - dataset: ${hardware.paths.data}/${hardware.files.dataset_y_forcings}
      name: hres
      select: ${dataloader.select_in_hres}
    - dataset: ${hardware.paths.data}/${hardware.files.dataset_y}
      name: out
      select: ${dataloader.select_out}
  adjust: dates
``` 

##  Additional notes ##

It may be possible to return a relevant metadata dict but I don't know
enough of the code to know what to return.

By opening this pull request, I affirm that all authors agree to the
[Contributor License
Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md)

---------

Co-authored-by: Aaron Hopkinson <aaron.hopkinson@ecmwf.int>