test(create): replace IGNORE with pytest.skip (#598)
## Description

Previously, a test in `tests/create/test_create.py` was ignored, and
thus silently skipped. Meaning when running that test, no output
indicated any tests were skipped. This PR marks the skipped test
explicitly.

## What issue or task does this change relate to?

https://github.com/ecmwf/anemoi-datasets/issues/591

##  Additional notes ##

Finding when `IGNORE` was added:

```
$ git blame tests/create/test_create.py | grep IGNORE
57a2895c3 (b8raoult        2026-01-22 11:23:42 +0000  31) IGNORE = ["recentre"]
57a2895c3 (b8raoult        2026-01-22 11:23:42 +0000  36)     if name in IGNORE:
```

But checking out this commit and running those tests reveals none of
them ever actually passed, including the originally ignored
`test_run[recentre]` test:

```
$ git checkout 57a2895c3
$ sed -i "s,IGNORE =.*,IGNORE = []," tests/create/test_create.py # force recentre test 
$ pytest -v --slow tests/create/test_create.py
FAILED tests/create/test_create.py::test_run[recentre] - ValueError: Argument 'availability' must be specified for accumulate source. See https://anemoi.readthedocs.io/projects/datasets/en/latest/building/sources/accumulate.html
FAILED tests/create/test_create.py::test_run[accumulate-mars-ea-oper] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[repeated-dates] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[accumulate-mars-ecland] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[accumulate-mars-od-oper] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[nan] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[accumulate-mars-reset] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[missing] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[accumulate-mars-ea-enda] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[concat] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[accumulate-mars-ea-oper-2] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[accumulate-mars-l5-oper] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[accumulate-mars-rr-oper] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[regrid] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[join] - AttributeError: 'dict' object has no attribute 'startswith'
FAILED tests/create/test_create.py::test_run[pipe] - AttributeError: 'dict' object has no attribute 'startswith'
====================================================================================== 
16 failed, 96 warnings in 9.13s 
=======================================================================================
```

Since commit 92d5ac955, all of those tests now pass except
`test_run[recentre]`.

***As a contributor to the Anemoi framework, please ensure that your
changes include unit tests, updates to any affected dependencies and
documentation, and have been tested in a parallel setting (i.e., with
multiple GPUs). As a reviewer, you are also responsible for verifying
these aspects and requesting changes if they are not adequately
addressed. For guidelines about those please refer to
https://anemoi.readthedocs.io/en/latest/***

By opening this pull request, I affirm that all authors agree to the
[Contributor License
Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md)

Co-authored-by: Ana Prieto Nemesio <91897203+anaprietonem@users.noreply.github.com>